### ISSUE TITLE
Package chisel4ml.transform us broken

### ISSUE THREAD

**Issue by AnouarITI** [cs-jsi/chisel4ml#4]
I tried to test your tool, and I followed the installation instructions, However, when I ran testing, I get the following:
<img width="569" alt="image" src="https://github.com/cs-jsi/chisel4ml/assets/96414784/6d3d6a40-3346-4159-b939-0e4b7a937617">

How Can I fix this issue?

**Comment by jurevreca12** [comment]
Hello.
Thanks for trying out the tool. Which branch did you clone?

**Comment by jurevreca12** [comment]
Yes that is a correct one. hm. this is wierd. Which operating system are you using?

**Comment by jurevreca12** [comment]
Ah. I think I see the problem. Likely your python version is to low. Could you try with python 3.10 or 3.9?
We still didn't get the continos integration cycle properly running so problems with versions could happen.

**Comment by AnouarITI** [comment]
I think you are correct I am using Python3.8, I will check this. Thank you :)
